### ISSUE TITLE
是我哪儿没搞对吗 

### ISSUE THREAD

**Issue by SuperZero1** [wotermelon/toJump#8]
![err](https://user-images.githubusercontent.com/15085293/34516171-db7c3dbc-f0b0-11e7-8bfc-d1bd4fa89ab6.png)
![err1](https://user-images.githubusercontent.com/15085293/34516175-e21d6358-f0b0-11e7-91a1-1aff7e207758.png)

**Comment by SuperZero1** [comment]
![err2](https://user-images.githubusercontent.com/15085293/34516303-66312544-f0b1-11e7-9d80-806acd049390.png)

**Comment by hhhuaang** [comment]
我也是这样

**Comment by moonou** [comment]
目测是adb文件权限问题，可以单独设置下adb文件的权限。

**Comment by wotermelon** [comment]
@SuperZero1 @hhhuaang 
由于系统原因，mac需要配置android的环境变量

[配置adb](http://blog.sina.com.cn/s/blog_540316260101ftge.html)

**Comment by SuperZero1** [comment]
现在可以了  但是加载缓慢 而且跳的距离其实波动很大 想要高分基本不可能。

**Comment by moonou** [comment]
波动请调整config.js里面的magicNumber，手机分辨率不同，数值也不同




    
    
    


    
        
            
                
                    
                            
                                
                            
                            
                                Moonou Long
                            
                    
                        
                            
                                    邮箱：moonoulong@gmail.com
                            
                        
                
            
        
    

签名由 网易邮箱大师 定制
在2018年01月04日 00:18，SuperZero1 写道： 现在可以了  但是加载缓慢 而且跳的距离其实波动很大 想要高分基本不可能。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wotermelon/toJump","title":"wotermelon/toJump","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wotermelon/toJump"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SuperZero1 in #8: 现在可以了  但是加载缓慢 而且跳的距离其实波动很大 想要高分基本不可能。"}],"action":{"name":"View Issue","url":"https://github.com/wotermelon/toJump/issues/8#issuecomment-355053581"}}}
